# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ae009083da805c61c1ec6aa77d7aa3a0fb261e72b46264480880c8505380aeafd4a997185073848614f3e336c9bdf32155d4d4c2bb65a78eb72a864f3de9d90

test:
  secret_key_base: 2b81319984500975949151b471b0cee7b9c3cc335f62cc75548f816d13d19dd74ec735624de9e664615d2c6781ee568c90ad1d3cf5ac8b47b754d85661e18cee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
